repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
        exclude: '\.ipynb$'
      - id: end-of-file-fixer
        exclude: '\.ipynb$'
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: pretty-format-json
        args: ['--autofix']
        exclude: '\.ipynb$'
      - id: check-added-large-files
        exclude: '\.ipynb$'

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.6
    hooks:
      - id: ruff
        args: [--fix]
        exclude: '^(examples/|ms/)'
      - id: ruff-format
        exclude: '^(examples/|ms/)'
